Repository mabraham123/AgileProject, pull requests merged in 2020-02, with the labels that each got.

#15 Updated Product backlog after Sprint Review
  Sprint 2/Product Backlog.xlsx
Labels: documentation

#16 Updated new product backlog for sprint 2
  Product Backlog (1).xlsx
Labels: documentation

#26 Sprint 1 Retrospective
  Sprint 2/Sprint 1 Retrospective.docx
Labels: documentation

#25 Create .gitignore
  Software_Code/.gitignore
Labels: enhancement

#27 Gitignore
  .gitignore
  Software_Code/.gitignore
  Software_Code/AgileJavaHospitalProject/.DS_Store
  Software_Code/AgileJavaHospitalProject/.gitignore
  Software_Code/AgileJavaHospitalProject/build/test/classes/TreatmentFinder/DatabaseTest.class
  Software_Code/AgileJavaHospitalProject/build/test/results/TEST-TreatmentFinder.DatabaseTest.xml
  Software_Code/AgileJavaHospitalProject/build/test/results/TESTS-TestSuites.xml
  Software_Code/AgileJavaHospitalProject/build/test/results/html/all-tests.html
  Software_Code/AgileJavaHospitalProject/build/test/results/html/allclasses-frame.html
  Software_Code/AgileJavaHospitalProject/build/test/results/html/alltests-errors.html
  Software_Code/AgileJavaHospitalProject/build/test/results/html/alltests-fails.html
  Software_Code/AgileJavaHospitalProject/build/test/results/html/alltests-skipped.html
  Software_Code/AgileJavaHospitalProject/build/test/results/html/index.html
  Software_Code/AgileJavaHospitalProject/build/test/results/html/overview-frame.html
  Software_Code/AgileJavaHospitalProject/build/test/results/html/overview-summary.html
  Software_Code/AgileJavaHospitalProject/build/test/results/html/stylesheet.css
  Software_Code/AgileJavaHospitalProject/build/web/META-INF/MANIFEST.MF
  Software_Code/AgileJavaHospitalProject/build/web/META-INF/context.xml
  Software_Code/AgileJavaHospitalProject/build/web/WEB-INF/classes/TreatmentFinder/Database.class
  Software_Code/AgileJavaHospitalProject/build/web/WEB-INF/lib/mysql-connector-java-8.0.19.jar
  Software_Code/AgileJavaHospitalProject/build/web/index.html
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/lib/CopyLibs/org-netbeans-modules-java-j2seproject-copylibstask.jar
  Software_Code/AgileJavaHospitalProject/lib/derbyclient.jar
  Software_Code/AgileJavaHospitalProject/lib/hamcrest/hamcrest-core-1.3.jar
  Software_Code/AgileJavaHospitalProject/lib/javaee-endorsed-api-7.0/javax.annotation-api.jar
  Software_Code/AgileJavaHospitalProject/lib/javaee-endorsed-api-7.0/javax.xml.soap-api.jar
  Software_Code/AgileJavaHospitalProject/lib/javaee-endorsed-api-7.0/jaxb-api-osgi.jar
  Software_Code/AgileJavaHospitalProject/lib/javaee-endorsed-api-7.0/jaxws-api.jar
  Software_Code/AgileJavaHospitalProject/lib/javaee-endorsed-api-7.0/jsr181-api.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_4/junit-4.12-javadoc.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_4/junit-4.12-sources.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_4/junit-4.12.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-api-5.3.1-javadoc.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-api-5.3.1-sources.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-api-5.3.1.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-engine-5.3.1-javadoc.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-engine-5.3.1-sources.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-engine-5.3.1.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-params-5.3.1-javadoc.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-params-5.3.1-sources.jar
  Software_Code/AgileJavaHospitalProject/lib/junit_5/junit-jupiter-params-5.3.1.jar
  Software_Code/AgileJavaHospitalProject/lib/mysql-connector-java-8.0.19.jar
  Software_Code/AgileJavaHospitalProject/nbproject/ant-deploy.xml
  Software_Code/AgileJavaHospitalProject/nbproject/build-impl.xml
  Software_Code/AgileJavaHospitalProject/nbproject/genfiles.properties
  Software_Code/AgileJavaHospitalProject/nbproject/private/private.properties
  Software_Code/AgileJavaHospitalProject/nbproject/private/private.xml
  Software_Code/AgileJavaHospitalProject/nbproject/project.properties
  Software_Code/AgileJavaHospitalProject/nbproject/project.xml
  Software_Code/AgileJavaHospitalProject/web/.DS_Store
Labels: enhancement

#30 Splitting code/description searches
  Software_Code/AgileJavaHospitalProject/web/index.html
  Software_Code/AgileJavaHospitalProject/web/search.jsp
Labels: enhancement

#32 Declutter and allow user to choose search
  Software_Code/AgileJavaHospitalProject/build/web/index.html
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/index.html
  Software_Code/AgileJavaHospitalProject/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/style.css
Labels: enhancement

#33 Modal and search feature
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/nbproject/private/private.xml
  Software_Code/AgileJavaHospitalProject/web/img/marker.png
  Software_Code/AgileJavaHospitalProject/web/search.jsp
Labels: Code Review, enhancement

#34 Search input display
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/search.jsp
Labels: enhancement

#39 Backbutton plus annimation plus footerfix
  Software_Code/AgileJavaHospitalProject/build/web/index.html
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/index.html
  Software_Code/AgileJavaHospitalProject/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/style.css
Labels: enhancement

#40 Favicon
  Software_Code/AgileJavaHospitalProject/build/web/index.html
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/img/android-chrome-192x192.png
  Software_Code/AgileJavaHospitalProject/web/img/android-chrome-512x512.png
  Software_Code/AgileJavaHospitalProject/web/img/apple-touch-icon.png
  Software_Code/AgileJavaHospitalProject/web/img/favicon-16x16.png
  Software_Code/AgileJavaHospitalProject/web/img/favicon-32x32.png
  Software_Code/AgileJavaHospitalProject/web/img/favicon.ico
  Software_Code/AgileJavaHospitalProject/web/img/site.webmanifest
  Software_Code/AgileJavaHospitalProject/web/index.html
  Software_Code/AgileJavaHospitalProject/web/search.jsp
Labels: enhancement

#41 New sprint backlog
  Sprint 2/Sprint 2 Backlog (1).xlsx
Labels: Daily Scrums

#42 Find on map
  Software_Code/AgileJavaHospitalProject/build/test/results/TEST-TreatmentFinder.DatabaseTest.xml
  Software_Code/AgileJavaHospitalProject/build/test/results/TESTS-TestSuites.xml
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/nbproject/private/private.properties
  Software_Code/AgileJavaHospitalProject/nbproject/project.properties
  Software_Code/AgileJavaHospitalProject/web/WEB-INF/classes/.netbeans_automatic_build
  Software_Code/AgileJavaHospitalProject/web/WEB-INF/classes/.netbeans_update_resources
  Software_Code/AgileJavaHospitalProject/web/WEB-INF/classes/org/json/.gitignore
  Software_Code/AgileJavaHospitalProject/web/WEB-INF/classes/org/json/LICENSE
  Software_Code/AgileJavaHospitalProject/web/WEB-INF/classes/org/json/README.md
  Software_Code/AgileJavaHospitalProject/web/WEB-INF/lib/mysql-connector-java-8.0.19.jar
  Software_Code/AgileJavaHospitalProject/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/style.css
Labels: Code Review

#45 Modal and search
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/style.css
Labels: Code Review, enhancement

#47 fix for leading 0's in drg code
  Software_Code/AgileJavaHospitalProject/web/index.html
Labels: enhancement

#48 Sprint backlog update
  Sprint 2/Sprint 2 Backlog (1).xlsx
Labels: Daily Scrums

#50 Updated Sprint 1 Retrospective. Now in paragraph format
  Sprint 2/Sprint 1 Retrospective.docx
Labels: documentation

#51 Changed dropdown for distance to numerical input
  Software_Code/AgileJavaHospitalProject/build/web/WEB-INF/classes/TreatmentFinder/Database.class
  Software_Code/AgileJavaHospitalProject/build/web/index.html
  Software_Code/AgileJavaHospitalProject/web/index.html
Labels: Code Review

#53 Error message
  Software_Code/AgileJavaHospitalProject/web/index.jsp
  Software_Code/AgileJavaHospitalProject/web/search.jsp
Labels: Code Review, enhancement

#54 fixed merge issues caused by using different versions of index file
  Software_Code/AgileJavaHospitalProject/build/web/index.html
  Software_Code/AgileJavaHospitalProject/build/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/index.jsp
  Software_Code/AgileJavaHospitalProject/web/search.jsp
Labels: Code Review

#55 Added unit tests for exisitng Java classes
  Software_Code/AgileJavaHospitalProject/build/test/classes/TreatmentFinder/DatabaseTest.class
  Software_Code/AgileJavaHospitalProject/build/test/results/TEST-TreatmentFinder.DatabaseTest.xml
  Software_Code/AgileJavaHospitalProject/build/web/WEB-INF/classes/TreatmentFinder/Database.class
  Software_Code/AgileJavaHospitalProject/nbproject/private/private.properties
  Software_Code/AgileJavaHospitalProject/nbproject/project.properties
  Software_Code/AgileJavaHospitalProject/test/TreatmentFinder/DatabaseTest.java
  Software_Code/AgileJavaHospitalProject/test/TreatmentFinder/HelperTest.java
  Software_Code/AgileJavaHospitalProject/test/TreatmentFinder/LocationManagerTest.java
Labels: testing

#56 Updated Sprint 2 Backlog for Day 3
  Sprint 2/Sprint 2 Backlog (2).xlsx
Labels: Daily Scrums

#57 Sprint 2 Report
  Sprint 2/Sprint 2 Report.docx
Labels: documentation

#59 TDD Report
  Sprint 2/TDD Report.docx
Labels: documentation

#61 TDD Roadmap Doc
  Sprint 2/TDD Roadmap.docx
Labels: coursework

#63 Search page redo, some other small changes
  Software_Code/AgileJavaHospitalProject/web/index.jsp
  Software_Code/AgileJavaHospitalProject/web/search.jsp
  Software_Code/AgileJavaHospitalProject/web/style.css
Labels: enhancement

#64 Sprint backlog for Thursday
  Sprint 2/Sprint 2 Backlog (3).xlsx
Labels: Daily Scrums

#69 Add data-order to fix sorting by distance
  Software_Code/AgileJavaHospitalProject/web/search.jsp
Labels: enhancement

#70 Adding back button
  Software_Code/AgileJavaHospitalProject/web/search.jsp
Labels: enhancement

#71 TDD Report
  Sprint 2/TDD Report.docx
Labels: coursework
